"use client";

import {
  BariPillarScore,
  BariScoreResult,
  PILLAR_LABEL,
  PILLAR_SUBTITLE,
  TIER_VERDICT,
  getExecutiveSummary,
  getPillarActions,
  getPillarBody,
  getRoadmap,
} from "@/lib/bari-scoring";
import { BariRevenueModelEnum, NumEmployeeEnum } from "@prisma/client";
import dayjs from "dayjs";
import { ArrowLeft, Download, Share2 } from "lucide-react";
import Link from "next/link";

interface BARIReportSVPProps {
  assessmentId: string;
  industryName: string | null;
  teamSize: NumEmployeeEnum | null;
  revenueModel: BariRevenueModelEnum | null;
  completedAt: string | null;
  createdAt: string;
  score: BariScoreResult;
}

const PILLAR_ORDER: BariPillarScore["pillar"][] = [
  "data_foundation",
  "process_digitisation",
  "ai_adoption_baseline",
  "team_readiness",
  "ai_search_visibility",
  "disruption_exposure",
];

function tierClass(label: BariPillarScore["tier_label"]) {
  switch (label) {
    case "Strength":
      return {
        text: "text-[#e8e6e1]",
        fill: "bg-[#e8e6e1]",
        dot: "bg-[#e8e6e1]",
      };
    case "Developing":
      return { text: "text-[#8a8780]", fill: "bg-[#8a8780]", dot: "bg-[#8a8780]" };
    case "Gap":
      return {
        text: "text-[#a8615e]/80",
        fill: "bg-[#a8615e]/70",
        dot: "bg-[#a8615e]/70",
      };
    case "Not Assessed":
      return {
        text: "text-[#5a5853]",
        fill: "bg-[#3d3a36]",
        dot: "bg-[#3d3a36]",
      };
  }
}

export default function BARIReportSVP(props: BARIReportSVPProps) {
  const { score } = props;
  const dateLabel = dayjs(
    props.completedAt ?? props.createdAt
  ).format("MMMM YYYY");
  const summary = getExecutiveSummary(score);
  const roadmap = getRoadmap(score);

  return (
    <div
      className="relative min-h-screen"
      style={{ background: "#0a0908", color: "#f5f4f0" }}
    >
      <div className="max-w-[1100px] mx-auto px-6 md:px-10 py-8 md:py-14">
        {/* Top return link */}
        <Link
          href="/business-ai-readiness-index/assesments"
          className="inline-flex items-center gap-2 font-jetbrains text-[10px] tracking-[2px] uppercase text-[#5a5853] hover:text-[#8a8780] transition-colors mb-6"
        >
          <ArrowLeft className="size-3" />
          Back to assessments
        </Link>

        <div className="rounded-[20px] overflow-hidden bg-[#111110] border border-[#2a2826]">
          {/* App bar */}
          <div className="h-[60px] bg-[#0a0908]/90 backdrop-blur border-b border-[#2a2826] flex items-center justify-between px-6">
            <span className="font-cormorant text-lg font-medium text-[#f5f4f0] tracking-[0.3px]">
              BARI
            </span>
            <div className="flex-1" />
            <div className="flex items-center gap-2.5">
              <button
                type="button"
                className="inline-flex items-center gap-1.5 font-medium font-read rounded-full px-4 h-9 text-[12px] bg-transparent text-[#c9c6bf] border border-[#3d3a36] hover:border-[#5a5853] hover:text-[#f5f4f0] transition-colors"
              >
                <Download className="size-3.5" />
                Download PDF
              </button>
              <button
                type="button"
                className="inline-flex items-center gap-1.5 font-medium font-read rounded-full px-4 h-9 text-[12px] bg-transparent text-[#c9c6bf] border border-[#3d3a36] hover:border-[#5a5853] hover:text-[#f5f4f0] transition-colors"
              >
                <Share2 className="size-3.5" />
                Share
              </button>
            </div>
          </div>

          <div className="px-8 md:px-16 py-12 md:py-14">
            {/* ── Cover ── */}
            <ReportCover
              score={score}
              dateLabel={dateLabel}
              context={{
                industry: props.industryName,
                teamSize: props.teamSize,
                revenueModel: props.revenueModel,
              }}
            />

            {/* ── Executive summary + score table ── */}
            <ExecutiveSummary summary={summary} score={score} />

            {/* ── Per-pillar sections ── */}
            {PILLAR_ORDER.map((pillarKey) => {
              const p = score.pillars[pillarKey];
              return <PillarSection key={pillarKey} pillar={p} />;
            })}

            {/* ── Roadmap ── */}
            <RoadmapSection
              roadmap={roadmap}
              ambition={score.qualitative["Q15"]}
            />

            {/* ── Closing ── */}
            <ClosingSection score={score} />

            {/* ── Footer row ── */}
            <div className="flex items-center justify-between pt-6 border-t border-[#2a2826] font-jetbrains text-[9px] tracking-[1.5px] uppercase text-[#5a5853]">
              <span>BARI — Business AI Readiness Index</span>
              <span>Sevenpreneur · {dateLabel}</span>
              <span className="hidden md:inline">
                Generated by Sevenpreneur × Claude AI
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Cover ───────────────────────────────────────────────

function ReportCover(props: {
  score: BariScoreResult;
  dateLabel: string;
  context: {
    industry: string | null;
    teamSize: NumEmployeeEnum | null;
    revenueModel: BariRevenueModelEnum | null;
  };
}) {
  const { score } = props;
  const verdict = TIER_VERDICT[score.tier.code];

  return (
    <div className="grid grid-cols-1 md:grid-cols-[1fr_auto] gap-12 items-start pb-12 mb-12 border-b border-[#2a2826]">
      <div>
        <div className="font-jetbrains text-[9px] tracking-[3px] uppercase text-[#8a8780] mb-4">
          BARI — Business AI Readiness Index · {props.dateLabel}
          {score.is_partial ? " · Stage 1" : ""}
        </div>
        <span
          className="font-cormorant font-light block mb-1"
          style={{
            fontSize: 88,
            lineHeight: 1,
            letterSpacing: "-4px",
            background:
              "linear-gradient(180deg, #f5f4f0 0%, #c9c6bf 50%, #6e6c66 100%)",
            WebkitBackgroundClip: "text",
            backgroundClip: "text",
            WebkitTextFillColor: "transparent",
          }}
        >
          {score.total_score}
        </span>
        <div className="font-cormorant text-2xl italic text-[#e8e6e1] tracking-[-0.2px]">
          {score.tier.label}
        </div>
        <div
          className="font-cormorant font-light italic text-[#8a8780] mt-4 max-w-[480px]"
          style={{ fontSize: 18, lineHeight: 1.55 }}
        >
          &ldquo;{verdict}&rdquo;
        </div>

        {(props.context.industry || props.context.teamSize) && (
          <div className="flex items-center flex-wrap gap-x-5 gap-y-2 mt-6 font-jetbrains text-[10px] tracking-[1.5px] uppercase text-[#5a5853]">
            {props.context.industry && (
              <span>Industry · {props.context.industry}</span>
            )}
            {props.context.teamSize && (
              <span>Team · {teamSizeLabel(props.context.teamSize)}</span>
            )}
            {props.context.revenueModel && (
              <span>Revenue · {revenueModelLabel(props.context.revenueModel)}</span>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

function teamSizeLabel(t: NumEmployeeEnum) {
  switch (t) {
    case "SMALL":
      return "Solo / 2";
    case "MEDIUM":
      return "3–10";
    case "LARGE":
      return "11–50";
    case "XLARGE":
      return "51–200";
    case "XXLARGE":
      return "200+";
  }
}

function revenueModelLabel(r: BariRevenueModelEnum) {
  switch (r) {
    case "PRODUCTS":
      return "Products";
    case "SERVICES":
      return "Services";
    case "SUBSCRIPTION":
      return "Subscription";
    case "MARKETPLACE":
      return "Marketplace";
    case "MIXED":
      return "Mixed";
  }
}

// ── Executive summary ────────────────────────────────────

function ExecutiveSummary(props: {
  summary: string[];
  score: BariScoreResult;
}) {
  return (
    <div className="mb-12 pb-12 border-b border-[#2a2826]">
      <div className="font-jetbrains text-[9px] tracking-[3px] uppercase text-[#8a8780] mb-6">
        Executive summary
      </div>

      <div
        className="font-cormorant font-light text-[#c9c6bf] max-w-[740px]"
        style={{ fontSize: 19, lineHeight: 1.7 }}
      >
        {props.summary.map((p, i) => (
          <p key={i} className={i > 0 ? "mt-4" : ""}>
            {p}
          </p>
        ))}
      </div>

      <ScoreTable score={props.score} />
    </div>
  );
}

function ScoreTable(props: { score: BariScoreResult }) {
  return (
    <table className="w-full border-collapse mt-8">
      <thead>
        <tr>
          <th className="font-jetbrains text-[8px] tracking-[2px] uppercase text-[#5a5853] text-left pb-3 border-b border-[#2a2826]">
            Pillar
          </th>
          <th className="font-jetbrains text-[8px] tracking-[2px] uppercase text-[#5a5853] text-left pb-3 border-b border-[#2a2826] w-[120px]" />
          <th className="font-jetbrains text-[8px] tracking-[2px] uppercase text-[#5a5853] text-right pb-3 border-b border-[#2a2826]">
            Score
          </th>
          <th className="font-jetbrains text-[8px] tracking-[2px] uppercase text-[#5a5853] text-right pb-3 border-b border-[#2a2826]">
            Status
          </th>
        </tr>
      </thead>
      <tbody>
        {PILLAR_ORDER.map((key) => {
          const p = props.score.pillars[key];
          const t = tierClass(p.tier_label);
          const fillPct = p.pillar_weight === 0 ? 0 : Math.min(100, (p.normalised / p.pillar_weight) * 100);
          return (
            <tr key={key} className="border-b border-[#1f1d1b] last:border-b-0">
              <td className="py-3 font-read text-[13px] text-[#c9c6bf]">
                {PILLAR_LABEL[key]}
              </td>
              <td className="py-3 pr-4">
                <span className="inline-block w-20 h-0.5 bg-[#2a2826] rounded-full overflow-hidden align-middle">
                  <span
                    className={`block h-0.5 rounded-full ${t.fill}`}
                    style={{ width: `${fillPct}%` }}
                  />
                </span>
              </td>
              <td
                className="py-3 text-right font-jetbrains text-[12px]"
                style={{
                  background:
                    "linear-gradient(180deg, #f5f4f0 0%, #8a8780 100%)",
                  WebkitBackgroundClip: "text",
                  backgroundClip: "text",
                  WebkitTextFillColor: "transparent",
                }}
              >
                {p.tier_label === "Not Assessed"
                  ? "— / —"
                  : `${p.normalised.toFixed(1)} / ${p.pillar_weight}`}
              </td>
              <td
                className={`py-3 text-right text-[10px] tracking-[0.5px] uppercase ${t.text}`}
              >
                {p.tier_label}
              </td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
}

// ── Pillar section ────────────────────────────────────────

function PillarSection(props: { pillar: BariPillarScore }) {
  const { pillar } = props;
  const t = tierClass(pillar.tier_label);
  const isAssessed = pillar.tier_label !== "Not Assessed";
  const body = isAssessed ? getPillarBody(pillar.pillar, pillar) : null;
  const actions = isAssessed ? getPillarActions(pillar.pillar, pillar) : [];

  return (
    <div className="mb-12 pb-12 border-b border-[#2a2826] last:border-b-0">
      <div className="flex items-start justify-between gap-6 mb-6">
        <h3
          className="font-cormorant font-normal"
          style={{ fontSize: 36, lineHeight: 1.1, letterSpacing: "-0.8px" }}
        >
          {PILLAR_LABEL[pillar.pillar]} —
          <br />
          <em className="italic">{PILLAR_SUBTITLE[pillar.pillar]}</em>
        </h3>
        <div className="text-right shrink-0">
          <span
            className="font-cormorant font-light block mb-1"
            style={{
              fontSize: 48,
              lineHeight: 1,
              letterSpacing: "-2px",
              background:
                "linear-gradient(180deg, #f5f4f0 0%, #8a8780 100%)",
              WebkitBackgroundClip: "text",
              backgroundClip: "text",
              WebkitTextFillColor: "transparent",
            }}
          >
            {isAssessed ? pillar.normalised.toFixed(1) : "—"}
          </span>
          <div className="font-jetbrains text-[10px] tracking-[1px] text-[#8a8780] mb-1">
            / {pillar.pillar_weight}
          </div>
          <span
            className={`font-jetbrains text-[9px] tracking-[2px] uppercase ${t.text}`}
          >
            {pillar.tier_label}
          </span>
        </div>
      </div>

      {isAssessed && body ? (
        <div
          className="font-read text-[15px] text-[#c9c6bf] mb-7 max-w-[700px]"
          style={{ lineHeight: 1.75 }}
        >
          {body.map((p, i) => (
            <p key={i} className={i > 0 ? "mt-4" : ""}>
              {p}
            </p>
          ))}
        </div>
      ) : (
        <p className="font-cormorant italic text-[#8a8780] text-[15px] mb-7 leading-[1.6]">
          Not assessed in Stage 1. Complete Stage 2 to surface the full
          {" "}
          {PILLAR_LABEL[pillar.pillar].toLowerCase()} diagnostic.
        </p>
      )}

      {actions.length > 0 && (
        <div className="bg-[#161513] border border-[#2a2826] rounded-xl overflow-hidden">
          {actions.map((action, i) => (
            <div
              key={i}
              className={`flex items-start gap-4 px-5 py-3.5 font-read text-[13px] text-[#c9c6bf] leading-[1.55] ${
                i < actions.length - 1
                  ? "border-b border-[#1f1d1b]"
                  : ""
              }`}
            >
              <span className="font-jetbrains text-[9px] text-[#5a5853] tracking-[1px] pt-1 shrink-0">
                {String(i + 1).padStart(2, "0")}
              </span>
              <span>{action}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ── Roadmap ───────────────────────────────────────────────

function RoadmapSection(props: {
  roadmap: { phase: string; theme: string; milestones: string[] }[];
  ambition?: string;
}) {
  return (
    <div className="mb-12">
      <div className="font-jetbrains text-[9px] tracking-[3px] uppercase text-[#8a8780] mb-3">
        30-60-90 day adoption roadmap
      </div>
      {props.ambition ? (
        <p className="font-read text-[14px] text-[#8a8780] max-w-[700px] leading-[1.6] mb-7">
          Oriented toward your stated outcome: <em>&ldquo;{props.ambition}&rdquo;</em>.
        </p>
      ) : (
        <p className="font-read text-[14px] text-[#8a8780] max-w-[700px] leading-[1.6] mb-7">
          Sequenced around the gaps your assessment surfaced.
        </p>
      )}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {props.roadmap.map((phase) => (
          <div
            key={phase.phase}
            className="bg-[#161513] border border-[#2a2826] rounded-2xl p-6"
          >
            <div className="font-jetbrains text-[9px] tracking-[2.5px] uppercase text-[#5a5853] mb-2.5">
              {phase.phase}
            </div>
            <div
              className="font-cormorant font-normal italic text-[#e8e6e1] mb-5"
              style={{ fontSize: 20, lineHeight: 1.2 }}
            >
              {phase.theme}
            </div>
            <div className="flex flex-col gap-2.5">
              {phase.milestones.map((m, i) => (
                <div
                  key={i}
                  className="flex gap-2.5 items-start font-read text-[12px] text-[#c9c6bf] leading-[1.55]"
                >
                  <span className="text-[#5a5853] shrink-0 mt-0.5">→</span>
                  <span>{m}</span>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Closing ──────────────────────────────────────────────

function ClosingSection(props: { score: BariScoreResult }) {
  const tier = props.score.tier.label;
  const total = props.score.total_score;
  const sorted = Object.values(props.score.pillars)
    .filter((p) => p.tier_label !== "Not Assessed")
    .sort((a, b) => a.pct - b.pct);
  const weakest = sorted[0]
    ? PILLAR_LABEL[sorted[0].pillar].toLowerCase()
    : "your weakest pillar";

  return (
    <div className="bg-[#161513] border border-[#2a2826] rounded-2xl p-8 mb-8">
      <div
        className="font-cormorant font-light italic text-[#c9c6bf]"
        style={{ fontSize: 20, lineHeight: 1.65 }}
      >
        A score of {total} reflects a{" "}
        <em className="not-italic font-normal text-[#e8e6e1]">{tier}</em>{" "}
        position — clear about where you stand and where to move next. The
        single highest-leverage focus from here is {weakest}; everything else
        compounds once that foundation moves. Start with the first action in
        the matching section above. Measure. Repeat.
      </div>
    </div>
  );
}
