Project sevenpreneur {
  database_type: 'PostgreSQL'
  note: 'Database for Sevenpreneur'
}

/////////////////
// Enumeration //
/////////////////

enum status_enum {
  active
  inactive
}

enum learning_method_enum {
  online
  onsite
  hybrid
}

////////////
// Tables //
////////////

Table industries {
  id             smallint     [primary key]
  industry_name  varchar      [note: 'e.g. Information Technology']
  created_at     timestamptz
}

Table entrepreneur_stages {
  id          smallint     [primary key]
  stage_name  varchar      [note: 'e.g. Growth']
  created_at  timestamptz
}

Table roles {
  id          smallint     [primary key]
  name        varchar      [note: 'e.g. Administrator']
  permission  smallint
  created_at  timestamptz
  updated_at  timestamptz
}

Table users {
  id                  uuid         [primary key]
  full_name           varchar      [note: 'e.g. Budi Sadikin']
  email               varchar      [note: 'unique, e.g. budisadikin@gmail.com']
  avatar              varchar
  role_id             smallint     [ref: > roles.id]
  status              status_enum
  date_of_birth       date
  learning_goal       varchar
  entrepreneur_stage  smallint
  business_name       varchar
  industry_id         smallint
  created_at          timestamptz
  updated_at          timestamptz
  last_login          timestamptz
  deleted_at          timestamptz
}

Table tokens {
  id          integer      [primary key]
  user_id     uuid         [ref: > users.id]
  is_active   boolean
  token       text         [note: 'unique']
  created_at  timestamptz
}

Table cohorts {
  id            integer      [primary key]
  name          varchar
  description   varchar
  image         varchar
  status        status_enum
  slug_url      varchar
  start_date    timestamptz
  end_date      timestamptz
  published_at  timestamptz
  updated_at    timestamptz
  deleted_at    timestamptz
  deleted_by    uuid         [ref: > users.id]
}

Table cohort_prices {
  id          integer         [primary key]
  cohort_id   integer         [ref: > cohorts.id]
  name        varchar
  amount      decimal(12, 2)
  status      status_enum
  created_at  timestamptz
}

Table modules {
  id            integer      [primary key]
  cohort_id     integer      [ref: > cohorts.id]
  name          varchar
  description   varchar
  document_url  varchar
  status        status_enum
  created_at    timestamptz
  updated_at    timestamptz
}

Table learnings {
  id             integer               [primary key]
  cohort_id      integer               [ref: > cohorts.id]
  name           varchar
  description    varchar
  method         learning_method_enum
  meeting_date   timestamptz
  meeting_url    varchar
  location_name  varchar
  location_url   varchar
  speaker_id     uuid                  [ref: > users.id]
  recording_url  varchar
  status         status_enum
  created_at     timestamptz
  updated_at     timestamptz
}

Table materials {
  id            integer      [primary key]
  learning_id   integer      [ref: > learnings.id]
  name          varchar
  description   varchar
  document_url  varchar
  status        status_enum
  created_at    timestamptz
  updated_at    timestamptz
}

Table projects {
  id            integer      [primary key]
  cohort_id     integer      [ref: > cohorts.id]
  name          varchar
  description   varchar
  document_url  varchar
  deadline_at   timestamptz
  status        status_enum
  created_at    timestamptz
  updated_at    timestamptz
}
